// Code generated by protoc-gen-go.
// source: console_manage.proto
// DO NOT EDIT!

package protocol

import proto "code.google.com/p/goprotobuf/proto"
import json "encoding/json"
import math "math"

// Reference proto, json, and math imports to suppress error if they are not otherwise used.
var _ = proto.Marshal
var _ = &json.SyntaxError{}
var _ = math.Inf

// 迁移理由类型
type MigrateType int32

const (
	MigrateType_MigrateType_Crash  MigrateType = 1
	MigrateType_MigrateType_Manual MigrateType = 2
)

var MigrateType_name = map[int32]string{
	1: "MigrateType_Crash",
	2: "MigrateType_Manual",
}
var MigrateType_value = map[string]int32{
	"MigrateType_Crash":  1,
	"MigrateType_Manual": 2,
}

func (x MigrateType) Enum() *MigrateType {
	p := new(MigrateType)
	*p = x
	return p
}
func (x MigrateType) String() string {
	return proto.EnumName(MigrateType_name, int32(x))
}
func (x *MigrateType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(MigrateType_value, data, "MigrateType")
	if err != nil {
		return err
	}
	*x = MigrateType(value)
	return nil
}

type GatewayMigrateNotify struct {
	OriginalServerId   *int32       `protobuf:"varint,1,opt" json:"OriginalServerId,omitempty"`
	OriginalServerAddr *string      `protobuf:"bytes,2,opt" json:"OriginalServerAddr,omitempty"`
	NewServerId        *int32       `protobuf:"varint,3,opt" json:"NewServerId,omitempty"`
	NewServerAddr      *string      `protobuf:"bytes,4,opt" json:"NewServerAddr,omitempty"`
	MigrateReason      *MigrateType `protobuf:"varint,5,opt,enum=protocol.MigrateType" json:"MigrateReason,omitempty"`
	XXX_unrecognized   []byte       `json:"-"`
}

func (m *GatewayMigrateNotify) Reset()         { *m = GatewayMigrateNotify{} }
func (m *GatewayMigrateNotify) String() string { return proto.CompactTextString(m) }
func (*GatewayMigrateNotify) ProtoMessage()    {}

func (m *GatewayMigrateNotify) GetOriginalServerId() int32 {
	if m != nil && m.OriginalServerId != nil {
		return *m.OriginalServerId
	}
	return 0
}

func (m *GatewayMigrateNotify) GetOriginalServerAddr() string {
	if m != nil && m.OriginalServerAddr != nil {
		return *m.OriginalServerAddr
	}
	return ""
}

func (m *GatewayMigrateNotify) GetNewServerId() int32 {
	if m != nil && m.NewServerId != nil {
		return *m.NewServerId
	}
	return 0
}

func (m *GatewayMigrateNotify) GetNewServerAddr() string {
	if m != nil && m.NewServerAddr != nil {
		return *m.NewServerAddr
	}
	return ""
}

func (m *GatewayMigrateNotify) GetMigrateReason() MigrateType {
	if m != nil && m.MigrateReason != nil {
		return *m.MigrateReason
	}
	return MigrateType_MigrateType_Crash
}

type GatewayRegist struct {
	GatewayID                *int32  `protobuf:"varint,1,opt" json:"GatewayID,omitempty"`
	GatewayGameServerAddress *string `protobuf:"bytes,2,opt" json:"GatewayGameServerAddress,omitempty"`
	XXX_unrecognized         []byte  `json:"-"`
}

func (m *GatewayRegist) Reset()         { *m = GatewayRegist{} }
func (m *GatewayRegist) String() string { return proto.CompactTextString(m) }
func (*GatewayRegist) ProtoMessage()    {}

func (m *GatewayRegist) GetGatewayID() int32 {
	if m != nil && m.GatewayID != nil {
		return *m.GatewayID
	}
	return 0
}

func (m *GatewayRegist) GetGatewayGameServerAddress() string {
	if m != nil && m.GatewayGameServerAddress != nil {
		return *m.GatewayGameServerAddress
	}
	return ""
}

// 服务注册
type MiscSvrRegist struct {
	ServerId         *int32   `protobuf:"varint,1,opt" json:"ServerId,omitempty"`
	ServiceType      *int32   `protobuf:"varint,2,opt" json:"ServiceType,omitempty"`
	ServiceAddress   *string  `protobuf:"bytes,3,opt" json:"ServiceAddress,omitempty"`
	AppId            *int32   `protobuf:"varint,4,opt" json:"AppId,omitempty"`
	Cmd              []uint32 `protobuf:"varint,5,rep" json:"Cmd,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *MiscSvrRegist) Reset()         { *m = MiscSvrRegist{} }
func (m *MiscSvrRegist) String() string { return proto.CompactTextString(m) }
func (*MiscSvrRegist) ProtoMessage()    {}

func (m *MiscSvrRegist) GetServerId() int32 {
	if m != nil && m.ServerId != nil {
		return *m.ServerId
	}
	return 0
}

func (m *MiscSvrRegist) GetServiceType() int32 {
	if m != nil && m.ServiceType != nil {
		return *m.ServiceType
	}
	return 0
}

func (m *MiscSvrRegist) GetServiceAddress() string {
	if m != nil && m.ServiceAddress != nil {
		return *m.ServiceAddress
	}
	return ""
}

func (m *MiscSvrRegist) GetAppId() int32 {
	if m != nil && m.AppId != nil {
		return *m.AppId
	}
	return 0
}

func (m *MiscSvrRegist) GetCmd() []uint32 {
	if m != nil {
		return m.Cmd
	}
	return nil
}

// 服务注册
type NonCenterSvrRegist struct {
	ServerId         *int32  `protobuf:"varint,1,opt" json:"ServerId,omitempty"`
	ServerType       *int32  `protobuf:"varint,2,opt" json:"ServerType,omitempty"`
	ServerAddress    *string `protobuf:"bytes,3,opt" json:"ServerAddress,omitempty"`
	AppId            *int32  `protobuf:"varint,4,opt" json:"AppId,omitempty"`
	CodeSectionMin   *int32  `protobuf:"varint,5,opt" json:"CodeSectionMin,omitempty"`
	CodeSectionMax   *int32  `protobuf:"varint,6,opt" json:"CodeSectionMax,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *NonCenterSvrRegist) Reset()         { *m = NonCenterSvrRegist{} }
func (m *NonCenterSvrRegist) String() string { return proto.CompactTextString(m) }
func (*NonCenterSvrRegist) ProtoMessage()    {}

func (m *NonCenterSvrRegist) GetServerId() int32 {
	if m != nil && m.ServerId != nil {
		return *m.ServerId
	}
	return 0
}

func (m *NonCenterSvrRegist) GetServerType() int32 {
	if m != nil && m.ServerType != nil {
		return *m.ServerType
	}
	return 0
}

func (m *NonCenterSvrRegist) GetServerAddress() string {
	if m != nil && m.ServerAddress != nil {
		return *m.ServerAddress
	}
	return ""
}

func (m *NonCenterSvrRegist) GetAppId() int32 {
	if m != nil && m.AppId != nil {
		return *m.AppId
	}
	return 0
}

func (m *NonCenterSvrRegist) GetCodeSectionMin() int32 {
	if m != nil && m.CodeSectionMin != nil {
		return *m.CodeSectionMin
	}
	return 0
}

func (m *NonCenterSvrRegist) GetCodeSectionMax() int32 {
	if m != nil && m.CodeSectionMax != nil {
		return *m.CodeSectionMax
	}
	return 0
}

// 服务注册结果
type NonCenterSvrRegistResult struct {
	Result           *int32 `protobuf:"varint,1,opt" json:"Result,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *NonCenterSvrRegistResult) Reset()         { *m = NonCenterSvrRegistResult{} }
func (m *NonCenterSvrRegistResult) String() string { return proto.CompactTextString(m) }
func (*NonCenterSvrRegistResult) ProtoMessage()    {}

func (m *NonCenterSvrRegistResult) GetResult() int32 {
	if m != nil && m.Result != nil {
		return *m.Result
	}
	return 0
}

// 服务注册通知网关
type NonCenterSvrRegistNotify struct {
	ServerId         *int32  `protobuf:"varint,1,opt" json:"ServerId,omitempty"`
	ServerType       *int32  `protobuf:"varint,2,opt" json:"ServerType,omitempty"`
	ServerAddress    *string `protobuf:"bytes,3,opt" json:"ServerAddress,omitempty"`
	ServerState      *int32  `protobuf:"varint,4,opt" json:"ServerState,omitempty"`
	AppId            *int32  `protobuf:"varint,5,opt" json:"AppId,omitempty"`
	CodeSectionMin   *int32  `protobuf:"varint,6,opt" json:"CodeSectionMin,omitempty"`
	CodeSectionMax   *int32  `protobuf:"varint,7,opt" json:"CodeSectionMax,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *NonCenterSvrRegistNotify) Reset()         { *m = NonCenterSvrRegistNotify{} }
func (m *NonCenterSvrRegistNotify) String() string { return proto.CompactTextString(m) }
func (*NonCenterSvrRegistNotify) ProtoMessage()    {}

func (m *NonCenterSvrRegistNotify) GetServerId() int32 {
	if m != nil && m.ServerId != nil {
		return *m.ServerId
	}
	return 0
}

func (m *NonCenterSvrRegistNotify) GetServerType() int32 {
	if m != nil && m.ServerType != nil {
		return *m.ServerType
	}
	return 0
}

func (m *NonCenterSvrRegistNotify) GetServerAddress() string {
	if m != nil && m.ServerAddress != nil {
		return *m.ServerAddress
	}
	return ""
}

func (m *NonCenterSvrRegistNotify) GetServerState() int32 {
	if m != nil && m.ServerState != nil {
		return *m.ServerState
	}
	return 0
}

func (m *NonCenterSvrRegistNotify) GetAppId() int32 {
	if m != nil && m.AppId != nil {
		return *m.AppId
	}
	return 0
}

func (m *NonCenterSvrRegistNotify) GetCodeSectionMin() int32 {
	if m != nil && m.CodeSectionMin != nil {
		return *m.CodeSectionMin
	}
	return 0
}

func (m *NonCenterSvrRegistNotify) GetCodeSectionMax() int32 {
	if m != nil && m.CodeSectionMax != nil {
		return *m.CodeSectionMax
	}
	return 0
}

// 上报服务器信息（暂时人数）
type AppUpdateServerInfo struct {
	UserCount        *uint32 `protobuf:"varint,1,opt" json:"UserCount,omitempty"`
	UserTotalCount   *uint32 `protobuf:"varint,2,opt" json:"UserTotalCount,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *AppUpdateServerInfo) Reset()         { *m = AppUpdateServerInfo{} }
func (m *AppUpdateServerInfo) String() string { return proto.CompactTextString(m) }
func (*AppUpdateServerInfo) ProtoMessage()    {}

func (m *AppUpdateServerInfo) GetUserCount() uint32 {
	if m != nil && m.UserCount != nil {
		return *m.UserCount
	}
	return 0
}

func (m *AppUpdateServerInfo) GetUserTotalCount() uint32 {
	if m != nil && m.UserTotalCount != nil {
		return *m.UserTotalCount
	}
	return 0
}

// 服务注册
type AdminTest struct {
	ServerId         *int32  `protobuf:"varint,1,opt" json:"ServerId,omitempty"`
	String_          *string `protobuf:"bytes,2,opt" json:"String,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *AdminTest) Reset()         { *m = AdminTest{} }
func (m *AdminTest) String() string { return proto.CompactTextString(m) }
func (*AdminTest) ProtoMessage()    {}

func (m *AdminTest) GetServerId() int32 {
	if m != nil && m.ServerId != nil {
		return *m.ServerId
	}
	return 0
}

func (m *AdminTest) GetString_() string {
	if m != nil && m.String_ != nil {
		return *m.String_
	}
	return ""
}

// 更新console房间信息
type RoomInfoUpdate struct {
	RoomId           *uint32  `protobuf:"varint,1,opt" json:"RoomId,omitempty"`
	CreateUID        *uint32  `protobuf:"varint,2,opt" json:"CreateUID,omitempty"`
	RoomType         *uint32  `protobuf:"varint,3,opt" json:"RoomType,omitempty"`
	ServerID         *int32   `protobuf:"varint,4,opt" json:"ServerID,omitempty"`
	GameID           *int32   `protobuf:"varint,5,opt" json:"GameID,omitempty"`
	Players          []uint32 `protobuf:"varint,6,rep" json:"Players,omitempty"`
	Operate          *int32   `protobuf:"varint,7,opt" json:"Operate,omitempty"`
	ModelKind        *uint32  `protobuf:"varint,8,opt" json:"ModelKind,omitempty"`
	RoomCreateInfo   *string  `protobuf:"bytes,9,opt" json:"RoomCreateInfo,omitempty"`
	RealPlayerCount  *int32   `protobuf:"varint,10,opt" json:"RealPlayerCount,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *RoomInfoUpdate) Reset()         { *m = RoomInfoUpdate{} }
func (m *RoomInfoUpdate) String() string { return proto.CompactTextString(m) }
func (*RoomInfoUpdate) ProtoMessage()    {}

func (m *RoomInfoUpdate) GetRoomId() uint32 {
	if m != nil && m.RoomId != nil {
		return *m.RoomId
	}
	return 0
}

func (m *RoomInfoUpdate) GetCreateUID() uint32 {
	if m != nil && m.CreateUID != nil {
		return *m.CreateUID
	}
	return 0
}

func (m *RoomInfoUpdate) GetRoomType() uint32 {
	if m != nil && m.RoomType != nil {
		return *m.RoomType
	}
	return 0
}

func (m *RoomInfoUpdate) GetServerID() int32 {
	if m != nil && m.ServerID != nil {
		return *m.ServerID
	}
	return 0
}

func (m *RoomInfoUpdate) GetGameID() int32 {
	if m != nil && m.GameID != nil {
		return *m.GameID
	}
	return 0
}

func (m *RoomInfoUpdate) GetPlayers() []uint32 {
	if m != nil {
		return m.Players
	}
	return nil
}

func (m *RoomInfoUpdate) GetOperate() int32 {
	if m != nil && m.Operate != nil {
		return *m.Operate
	}
	return 0
}

func (m *RoomInfoUpdate) GetModelKind() uint32 {
	if m != nil && m.ModelKind != nil {
		return *m.ModelKind
	}
	return 0
}

func (m *RoomInfoUpdate) GetRoomCreateInfo() string {
	if m != nil && m.RoomCreateInfo != nil {
		return *m.RoomCreateInfo
	}
	return ""
}

func (m *RoomInfoUpdate) GetRealPlayerCount() int32 {
	if m != nil && m.RealPlayerCount != nil {
		return *m.RealPlayerCount
	}
	return 0
}

// 更新console玩家信息
type PlayerInfoUpdate struct {
	RoomId           *uint32 `protobuf:"varint,1,opt" json:"RoomId,omitempty"`
	RoomType         *uint32 `protobuf:"varint,2,opt" json:"RoomType,omitempty"`
	ServerID         *int32  `protobuf:"varint,3,opt" json:"ServerID,omitempty"`
	GameID           *int32  `protobuf:"varint,4,opt" json:"GameID,omitempty"`
	Uid              *uint32 `protobuf:"varint,5,opt" json:"Uid,omitempty"`
	Operate          *int32  `protobuf:"varint,6,opt" json:"Operate,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *PlayerInfoUpdate) Reset()         { *m = PlayerInfoUpdate{} }
func (m *PlayerInfoUpdate) String() string { return proto.CompactTextString(m) }
func (*PlayerInfoUpdate) ProtoMessage()    {}

func (m *PlayerInfoUpdate) GetRoomId() uint32 {
	if m != nil && m.RoomId != nil {
		return *m.RoomId
	}
	return 0
}

func (m *PlayerInfoUpdate) GetRoomType() uint32 {
	if m != nil && m.RoomType != nil {
		return *m.RoomType
	}
	return 0
}

func (m *PlayerInfoUpdate) GetServerID() int32 {
	if m != nil && m.ServerID != nil {
		return *m.ServerID
	}
	return 0
}

func (m *PlayerInfoUpdate) GetGameID() int32 {
	if m != nil && m.GameID != nil {
		return *m.GameID
	}
	return 0
}

func (m *PlayerInfoUpdate) GetUid() uint32 {
	if m != nil && m.Uid != nil {
		return *m.Uid
	}
	return 0
}

func (m *PlayerInfoUpdate) GetOperate() int32 {
	if m != nil && m.Operate != nil {
		return *m.Operate
	}
	return 0
}

// 更新游戏配置信息
type UpdateGameConfig struct {
	AppId            *int32  `protobuf:"varint,1,opt" json:"AppId,omitempty"`
	AppType          *int32  `protobuf:"varint,2,opt" json:"AppType,omitempty"`
	Type             *int32  `protobuf:"varint,3,opt" json:"Type,omitempty"`
	Uid              *uint32 `protobuf:"varint,4,opt" json:"Uid,omitempty"`
	Data             *string `protobuf:"bytes,5,opt" json:"Data,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *UpdateGameConfig) Reset()         { *m = UpdateGameConfig{} }
func (m *UpdateGameConfig) String() string { return proto.CompactTextString(m) }
func (*UpdateGameConfig) ProtoMessage()    {}

func (m *UpdateGameConfig) GetAppId() int32 {
	if m != nil && m.AppId != nil {
		return *m.AppId
	}
	return 0
}

func (m *UpdateGameConfig) GetAppType() int32 {
	if m != nil && m.AppType != nil {
		return *m.AppType
	}
	return 0
}

func (m *UpdateGameConfig) GetType() int32 {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return 0
}

func (m *UpdateGameConfig) GetUid() uint32 {
	if m != nil && m.Uid != nil {
		return *m.Uid
	}
	return 0
}

func (m *UpdateGameConfig) GetData() string {
	if m != nil && m.Data != nil {
		return *m.Data
	}
	return ""
}

// 更新游戏中营收信息
type UpdateRevenueInfo struct {
	AppID            *int32  `protobuf:"varint,1,opt" json:"AppID,omitempty"`
	AppType          *uint32 `protobuf:"varint,2,opt" json:"AppType,omitempty"`
	ServerID         *uint32 `protobuf:"varint,3,opt" json:"ServerID,omitempty"`
	RoomType         *uint32 `protobuf:"varint,4,opt" json:"RoomType,omitempty"`
	SessionID        *int32  `protobuf:"varint,5,opt" json:"SessionID,omitempty"`
	SysWinGold       *int64  `protobuf:"varint,6,opt" json:"SysWinGold,omitempty"`
	RobotWinGold     *int64  `protobuf:"varint,7,opt" json:"RobotWinGold,omitempty"`
	InputGold        *int64  `protobuf:"varint,8,opt" json:"InputGold,omitempty"`
	OutputGold       *int64  `protobuf:"varint,9,opt" json:"OutputGold,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *UpdateRevenueInfo) Reset()         { *m = UpdateRevenueInfo{} }
func (m *UpdateRevenueInfo) String() string { return proto.CompactTextString(m) }
func (*UpdateRevenueInfo) ProtoMessage()    {}

func (m *UpdateRevenueInfo) GetAppID() int32 {
	if m != nil && m.AppID != nil {
		return *m.AppID
	}
	return 0
}

func (m *UpdateRevenueInfo) GetAppType() uint32 {
	if m != nil && m.AppType != nil {
		return *m.AppType
	}
	return 0
}

func (m *UpdateRevenueInfo) GetServerID() uint32 {
	if m != nil && m.ServerID != nil {
		return *m.ServerID
	}
	return 0
}

func (m *UpdateRevenueInfo) GetRoomType() uint32 {
	if m != nil && m.RoomType != nil {
		return *m.RoomType
	}
	return 0
}

func (m *UpdateRevenueInfo) GetSessionID() int32 {
	if m != nil && m.SessionID != nil {
		return *m.SessionID
	}
	return 0
}

func (m *UpdateRevenueInfo) GetSysWinGold() int64 {
	if m != nil && m.SysWinGold != nil {
		return *m.SysWinGold
	}
	return 0
}

func (m *UpdateRevenueInfo) GetRobotWinGold() int64 {
	if m != nil && m.RobotWinGold != nil {
		return *m.RobotWinGold
	}
	return 0
}

func (m *UpdateRevenueInfo) GetInputGold() int64 {
	if m != nil && m.InputGold != nil {
		return *m.InputGold
	}
	return 0
}

func (m *UpdateRevenueInfo) GetOutputGold() int64 {
	if m != nil && m.OutputGold != nil {
		return *m.OutputGold
	}
	return 0
}

// 检测正在打牌的房间
type CDetectCurrentRoom struct {
	Uid              *uint32 `protobuf:"varint,1,opt" json:"Uid,omitempty"`
	IsServer         *int32  `protobuf:"varint,2,opt" json:"IsServer,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *CDetectCurrentRoom) Reset()         { *m = CDetectCurrentRoom{} }
func (m *CDetectCurrentRoom) String() string { return proto.CompactTextString(m) }
func (*CDetectCurrentRoom) ProtoMessage()    {}

func (m *CDetectCurrentRoom) GetUid() uint32 {
	if m != nil && m.Uid != nil {
		return *m.Uid
	}
	return 0
}

func (m *CDetectCurrentRoom) GetIsServer() int32 {
	if m != nil && m.IsServer != nil {
		return *m.IsServer
	}
	return 0
}

type SDetectCurrentRoom struct {
	Uid              *uint32 `protobuf:"varint,1,opt" json:"Uid,omitempty"`
	InviteCode       *uint32 `protobuf:"varint,2,opt" json:"InviteCode,omitempty"`
	AppID            *int32  `protobuf:"varint,3,opt" json:"AppID,omitempty"`
	ServerID         *int32  `protobuf:"varint,4,opt" json:"ServerID,omitempty"`
	Type             *int32  `protobuf:"varint,5,opt" json:"Type,omitempty"`
	IsServer         *int32  `protobuf:"varint,6,opt" json:"IsServer,omitempty"`
	Error            *uint32 `protobuf:"varint,7,opt" json:"Error,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *SDetectCurrentRoom) Reset()         { *m = SDetectCurrentRoom{} }
func (m *SDetectCurrentRoom) String() string { return proto.CompactTextString(m) }
func (*SDetectCurrentRoom) ProtoMessage()    {}

func (m *SDetectCurrentRoom) GetUid() uint32 {
	if m != nil && m.Uid != nil {
		return *m.Uid
	}
	return 0
}

func (m *SDetectCurrentRoom) GetInviteCode() uint32 {
	if m != nil && m.InviteCode != nil {
		return *m.InviteCode
	}
	return 0
}

func (m *SDetectCurrentRoom) GetAppID() int32 {
	if m != nil && m.AppID != nil {
		return *m.AppID
	}
	return 0
}

func (m *SDetectCurrentRoom) GetServerID() int32 {
	if m != nil && m.ServerID != nil {
		return *m.ServerID
	}
	return 0
}

func (m *SDetectCurrentRoom) GetType() int32 {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return 0
}

func (m *SDetectCurrentRoom) GetIsServer() int32 {
	if m != nil && m.IsServer != nil {
		return *m.IsServer
	}
	return 0
}

func (m *SDetectCurrentRoom) GetError() uint32 {
	if m != nil && m.Error != nil {
		return *m.Error
	}
	return 0
}

// 获取房间玩家信息
type CGetRoomPlayers struct {
	AppID            *int32 `protobuf:"varint,1,opt" json:"AppID,omitempty"`
	Type             *int32 `protobuf:"varint,2,opt" json:"Type,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *CGetRoomPlayers) Reset()         { *m = CGetRoomPlayers{} }
func (m *CGetRoomPlayers) String() string { return proto.CompactTextString(m) }
func (*CGetRoomPlayers) ProtoMessage()    {}

func (m *CGetRoomPlayers) GetAppID() int32 {
	if m != nil && m.AppID != nil {
		return *m.AppID
	}
	return 0
}

func (m *CGetRoomPlayers) GetType() int32 {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return 0
}

type SGetRoomPlayers struct {
	Uid              *uint32 `protobuf:"varint,1,opt" json:"Uid,omitempty"`
	ID               []int32 `protobuf:"varint,2,rep" json:"ID,omitempty"`
	PlayerCount      []int32 `protobuf:"varint,3,rep" json:"PlayerCount,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *SGetRoomPlayers) Reset()         { *m = SGetRoomPlayers{} }
func (m *SGetRoomPlayers) String() string { return proto.CompactTextString(m) }
func (*SGetRoomPlayers) ProtoMessage()    {}

func (m *SGetRoomPlayers) GetUid() uint32 {
	if m != nil && m.Uid != nil {
		return *m.Uid
	}
	return 0
}

func (m *SGetRoomPlayers) GetID() []int32 {
	if m != nil {
		return m.ID
	}
	return nil
}

func (m *SGetRoomPlayers) GetPlayerCount() []int32 {
	if m != nil {
		return m.PlayerCount
	}
	return nil
}

// 获取大厅人数
type CGetPlatformPlayers struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *CGetPlatformPlayers) Reset()         { *m = CGetPlatformPlayers{} }
func (m *CGetPlatformPlayers) String() string { return proto.CompactTextString(m) }
func (*CGetPlatformPlayers) ProtoMessage()    {}

type SGetPlatformPlayers struct {
	Uid              *uint32 `protobuf:"varint,1,opt" json:"Uid,omitempty"`
	PlayerCount      *int32  `protobuf:"varint,2,opt" json:"PlayerCount,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *SGetPlatformPlayers) Reset()         { *m = SGetPlatformPlayers{} }
func (m *SGetPlatformPlayers) String() string { return proto.CompactTextString(m) }
func (*SGetPlatformPlayers) ProtoMessage()    {}

func (m *SGetPlatformPlayers) GetUid() uint32 {
	if m != nil && m.Uid != nil {
		return *m.Uid
	}
	return 0
}

func (m *SGetPlatformPlayers) GetPlayerCount() int32 {
	if m != nil && m.PlayerCount != nil {
		return *m.PlayerCount
	}
	return 0
}

// 踢玩家下线
type SKickPlayerOffLine struct {
	Uid              *uint32 `protobuf:"varint,1,opt" json:"Uid,omitempty"`
	Type             *int32  `protobuf:"varint,2,opt" json:"Type,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *SKickPlayerOffLine) Reset()         { *m = SKickPlayerOffLine{} }
func (m *SKickPlayerOffLine) String() string { return proto.CompactTextString(m) }
func (*SKickPlayerOffLine) ProtoMessage()    {}

func (m *SKickPlayerOffLine) GetUid() uint32 {
	if m != nil && m.Uid != nil {
		return *m.Uid
	}
	return 0
}

func (m *SKickPlayerOffLine) GetType() int32 {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return 0
}

// 改变游戏服状态 0:停服 1:开服
type ChangeGameServer struct {
	Status           *int32 `protobuf:"varint,1,opt" json:"Status,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *ChangeGameServer) Reset()         { *m = ChangeGameServer{} }
func (m *ChangeGameServer) String() string { return proto.CompactTextString(m) }
func (*ChangeGameServer) ProtoMessage()    {}

func (m *ChangeGameServer) GetStatus() int32 {
	if m != nil && m.Status != nil {
		return *m.Status
	}
	return 0
}

// 刷新配置文件
type RefGameConfig struct {
	Type             *int32 `protobuf:"varint,1,opt" json:"Type,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *RefGameConfig) Reset()         { *m = RefGameConfig{} }
func (m *RefGameConfig) String() string { return proto.CompactTextString(m) }
func (*RefGameConfig) ProtoMessage()    {}

func (m *RefGameConfig) GetType() int32 {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return 0
}

// 更新奖池
type UpdateSysPrizePool struct {
	AppID            *int32 `protobuf:"varint,1,opt" json:"AppID,omitempty"`
	Type             *int32 `protobuf:"varint,2,opt" json:"Type,omitempty"`
	Prize            *int64 `protobuf:"varint,3,opt" json:"Prize,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *UpdateSysPrizePool) Reset()         { *m = UpdateSysPrizePool{} }
func (m *UpdateSysPrizePool) String() string { return proto.CompactTextString(m) }
func (*UpdateSysPrizePool) ProtoMessage()    {}

func (m *UpdateSysPrizePool) GetAppID() int32 {
	if m != nil && m.AppID != nil {
		return *m.AppID
	}
	return 0
}

func (m *UpdateSysPrizePool) GetType() int32 {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return 0
}

func (m *UpdateSysPrizePool) GetPrize() int64 {
	if m != nil && m.Prize != nil {
		return *m.Prize
	}
	return 0
}

// 获取房间列表
type CGetAppRoomList struct {
	AppID            *int32  `protobuf:"varint,1,opt" json:"AppID,omitempty"`
	Type             *int32  `protobuf:"varint,2,opt" json:"Type,omitempty"`
	CurPage          *int32  `protobuf:"varint,3,opt" json:"CurPage,omitempty"`
	ModelKind        *uint32 `protobuf:"varint,4,opt" json:"ModelKind,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *CGetAppRoomList) Reset()         { *m = CGetAppRoomList{} }
func (m *CGetAppRoomList) String() string { return proto.CompactTextString(m) }
func (*CGetAppRoomList) ProtoMessage()    {}

func (m *CGetAppRoomList) GetAppID() int32 {
	if m != nil && m.AppID != nil {
		return *m.AppID
	}
	return 0
}

func (m *CGetAppRoomList) GetType() int32 {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return 0
}

func (m *CGetAppRoomList) GetCurPage() int32 {
	if m != nil && m.CurPage != nil {
		return *m.CurPage
	}
	return 0
}

func (m *CGetAppRoomList) GetModelKind() uint32 {
	if m != nil && m.ModelKind != nil {
		return *m.ModelKind
	}
	return 0
}

// 房间信息
type AppRoomInfo struct {
	InviteCode       *uint32 `protobuf:"varint,1,opt" json:"InviteCode,omitempty"`
	ModelKind        *uint32 `protobuf:"varint,2,opt" json:"ModelKind,omitempty"`
	RoomCreateInfo   *string `protobuf:"bytes,3,opt" json:"RoomCreateInfo,omitempty"`
	PlayerCount      *int32  `protobuf:"varint,4,opt" json:"PlayerCount,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *AppRoomInfo) Reset()         { *m = AppRoomInfo{} }
func (m *AppRoomInfo) String() string { return proto.CompactTextString(m) }
func (*AppRoomInfo) ProtoMessage()    {}

func (m *AppRoomInfo) GetInviteCode() uint32 {
	if m != nil && m.InviteCode != nil {
		return *m.InviteCode
	}
	return 0
}

func (m *AppRoomInfo) GetModelKind() uint32 {
	if m != nil && m.ModelKind != nil {
		return *m.ModelKind
	}
	return 0
}

func (m *AppRoomInfo) GetRoomCreateInfo() string {
	if m != nil && m.RoomCreateInfo != nil {
		return *m.RoomCreateInfo
	}
	return ""
}

func (m *AppRoomInfo) GetPlayerCount() int32 {
	if m != nil && m.PlayerCount != nil {
		return *m.PlayerCount
	}
	return 0
}

type SGetAppRoomList struct {
	AppID            *int32         `protobuf:"varint,1,opt" json:"AppID,omitempty"`
	Type             *int32         `protobuf:"varint,2,opt" json:"Type,omitempty"`
	CurPage          *int32         `protobuf:"varint,3,opt" json:"CurPage,omitempty"`
	ModelKind        *uint32        `protobuf:"varint,4,opt" json:"ModelKind,omitempty"`
	RoomInfos        []*AppRoomInfo `protobuf:"bytes,5,rep" json:"RoomInfos,omitempty"`
	XXX_unrecognized []byte         `json:"-"`
}

func (m *SGetAppRoomList) Reset()         { *m = SGetAppRoomList{} }
func (m *SGetAppRoomList) String() string { return proto.CompactTextString(m) }
func (*SGetAppRoomList) ProtoMessage()    {}

func (m *SGetAppRoomList) GetAppID() int32 {
	if m != nil && m.AppID != nil {
		return *m.AppID
	}
	return 0
}

func (m *SGetAppRoomList) GetType() int32 {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return 0
}

func (m *SGetAppRoomList) GetCurPage() int32 {
	if m != nil && m.CurPage != nil {
		return *m.CurPage
	}
	return 0
}

func (m *SGetAppRoomList) GetModelKind() uint32 {
	if m != nil && m.ModelKind != nil {
		return *m.ModelKind
	}
	return 0
}

func (m *SGetAppRoomList) GetRoomInfos() []*AppRoomInfo {
	if m != nil {
		return m.RoomInfos
	}
	return nil
}

type NoticeChargeToGs struct {
	Uid              *uint32 `protobuf:"varint,1,req,name=uid" json:"uid,omitempty"`
	ChargeType       *int32  `protobuf:"varint,2,req,name=chargeType" json:"chargeType,omitempty"`
	ChargeGold       *int64  `protobuf:"varint,3,opt" json:"ChargeGold,omitempty"`
	ChargeRoomCard   *int64  `protobuf:"varint,4,opt" json:"ChargeRoomCard,omitempty"`
	ChargeDiamond    *int64  `protobuf:"varint,5,opt" json:"ChargeDiamond,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *NoticeChargeToGs) Reset()         { *m = NoticeChargeToGs{} }
func (m *NoticeChargeToGs) String() string { return proto.CompactTextString(m) }
func (*NoticeChargeToGs) ProtoMessage()    {}

func (m *NoticeChargeToGs) GetUid() uint32 {
	if m != nil && m.Uid != nil {
		return *m.Uid
	}
	return 0
}

func (m *NoticeChargeToGs) GetChargeType() int32 {
	if m != nil && m.ChargeType != nil {
		return *m.ChargeType
	}
	return 0
}

func (m *NoticeChargeToGs) GetChargeGold() int64 {
	if m != nil && m.ChargeGold != nil {
		return *m.ChargeGold
	}
	return 0
}

func (m *NoticeChargeToGs) GetChargeRoomCard() int64 {
	if m != nil && m.ChargeRoomCard != nil {
		return *m.ChargeRoomCard
	}
	return 0
}

func (m *NoticeChargeToGs) GetChargeDiamond() int64 {
	if m != nil && m.ChargeDiamond != nil {
		return *m.ChargeDiamond
	}
	return 0
}

func init() {
	proto.RegisterEnum("protocol.MigrateType", MigrateType_name, MigrateType_value)
}
