// Code generated by protoc-gen-go.
// source: login_objs.proto
// DO NOT EDIT!

package protocol

import proto "code.google.com/p/goprotobuf/proto"
import json "encoding/json"
import math "math"

// Reference proto, json, and math imports to suppress error if they are not otherwise used.
var _ = proto.Marshal
var _ = &json.SyntaxError{}
var _ = math.Inf

// 登录平台(微信/QQ)
type PF int32

const (
	PF_WECHAT PF = 1
)

var PF_name = map[int32]string{
	1: "WECHAT",
}
var PF_value = map[string]int32{
	"WECHAT": 1,
}

func (x PF) Enum() *PF {
	p := new(PF)
	*p = x
	return p
}
func (x PF) String() string {
	return proto.EnumName(PF_name, int32(x))
}
func (x *PF) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(PF_value, data, "PF")
	if err != nil {
		return err
	}
	*x = PF(value)
	return nil
}

// 玩家类型ID
type PlayerRole int32

const (
	PlayerRole_Player        PlayerRole = 0
	PlayerRole_SpecialAgent  PlayerRole = 1
	PlayerRole_OneLevelAgent PlayerRole = 2
	PlayerRole_TwoLevelAgent PlayerRole = 3
)

var PlayerRole_name = map[int32]string{
	0: "Player",
	1: "SpecialAgent",
	2: "OneLevelAgent",
	3: "TwoLevelAgent",
}
var PlayerRole_value = map[string]int32{
	"Player":        0,
	"SpecialAgent":  1,
	"OneLevelAgent": 2,
	"TwoLevelAgent": 3,
}

func (x PlayerRole) Enum() *PlayerRole {
	p := new(PlayerRole)
	*p = x
	return p
}
func (x PlayerRole) String() string {
	return proto.EnumName(PlayerRole_name, int32(x))
}
func (x *PlayerRole) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(PlayerRole_value, data, "PlayerRole")
	if err != nil {
		return err
	}
	*x = PlayerRole(value)
	return nil
}

// 玩家常用的数据
type LessUserData struct {
	Uid              *uint32 `protobuf:"varint,1,opt" json:"Uid,omitempty"`
	NickName         *string `protobuf:"bytes,2,opt" json:"NickName,omitempty"`
	RoomCard         *uint32 `protobuf:"varint,3,opt" json:"RoomCard,omitempty"`
	Icon             *string `protobuf:"bytes,4,opt" json:"Icon,omitempty"`
	Sex              *uint32 `protobuf:"varint,5,opt" json:"Sex,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *LessUserData) Reset()         { *m = LessUserData{} }
func (m *LessUserData) String() string { return proto.CompactTextString(m) }
func (*LessUserData) ProtoMessage()    {}

func (m *LessUserData) GetUid() uint32 {
	if m != nil && m.Uid != nil {
		return *m.Uid
	}
	return 0
}

func (m *LessUserData) GetNickName() string {
	if m != nil && m.NickName != nil {
		return *m.NickName
	}
	return ""
}

func (m *LessUserData) GetRoomCard() uint32 {
	if m != nil && m.RoomCard != nil {
		return *m.RoomCard
	}
	return 0
}

func (m *LessUserData) GetIcon() string {
	if m != nil && m.Icon != nil {
		return *m.Icon
	}
	return ""
}

func (m *LessUserData) GetSex() uint32 {
	if m != nil && m.Sex != nil {
		return *m.Sex
	}
	return 0
}

// 玩家的详细数据
type ProtoUser struct {
	Uid              *uint32 `protobuf:"varint,1,opt" json:"Uid,omitempty"`
	NickName         *string `protobuf:"bytes,2,opt" json:"NickName,omitempty"`
	Weixin           *string `protobuf:"bytes,3,opt" json:"Weixin,omitempty"`
	Seat             *uint32 `protobuf:"varint,4,opt" json:"Seat,omitempty"`
	Sex              *uint32 `protobuf:"varint,5,opt" json:"Sex,omitempty"`
	Photo            *string `protobuf:"bytes,7,opt" json:"Photo,omitempty"`
	Address          *string `protobuf:"bytes,8,opt" json:"Address,omitempty"`
	IP               *string `protobuf:"bytes,9,opt" json:"IP,omitempty"`
	Terminal         *string `protobuf:"bytes,10,opt" json:"Terminal,omitempty"`
	RoomCard         *uint32 `protobuf:"varint,12,opt" json:"RoomCard,omitempty"`
	Ready            *bool   `protobuf:"varint,13,opt" json:"Ready,omitempty"`
	InviteCode       *uint32 `protobuf:"varint,14,opt" json:"InviteCode,omitempty"`
	Score            *int32  `protobuf:"varint,15,opt" json:"Score,omitempty"`
	IsInputted       *bool   `protobuf:"varint,16,opt" json:"IsInputted,omitempty"`
	Role             *uint32 `protobuf:"varint,17,opt" json:"Role,omitempty"`
	IsSporting       *bool   `protobuf:"varint,18,opt" json:"IsSporting,omitempty"`
	Weixinno         *string `protobuf:"bytes,19,opt" json:"Weixinno,omitempty"`
	Upperid          *uint32 `protobuf:"varint,20,opt" json:"Upperid,omitempty"`
	Gold             *int64  `protobuf:"varint,21,opt" json:"Gold,omitempty"`
	CarryGold        *int64  `protobuf:"varint,22,opt" json:"CarryGold,omitempty"`
	SafeGold         *int64  `protobuf:"varint,23,opt" json:"SafeGold,omitempty"`
	Diamond          *int64  `protobuf:"varint,24,opt" json:"Diamond,omitempty"`
	CarryDiamond     *int64  `protobuf:"varint,25,opt" json:"CarryDiamond,omitempty"`
	SafeDiamond      *int64  `protobuf:"varint,26,opt" json:"SafeDiamond,omitempty"`
	LoginTypes       *string `protobuf:"bytes,27,opt" json:"LoginTypes,omitempty"`
	MatchCoin        *int64  `protobuf:"varint,28,opt" json:"MatchCoin,omitempty"`
	IsAgent          *bool   `protobuf:"varint,29,opt" json:"IsAgent,omitempty"`
	IsChooseSeat     *bool   `protobuf:"varint,30,opt" json:"IsChooseSeat,omitempty"`
	IsSuper          *int32  `protobuf:"varint,31,opt" json:"IsSuper,omitempty"`
	Coupons          *uint32 `protobuf:"varint,32,opt" json:"Coupons,omitempty"`
	Description      *string `protobuf:"bytes,33,opt" json:"Description,omitempty"`
	Phone            *string `protobuf:"bytes,34,opt" json:"Phone,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *ProtoUser) Reset()         { *m = ProtoUser{} }
func (m *ProtoUser) String() string { return proto.CompactTextString(m) }
func (*ProtoUser) ProtoMessage()    {}

func (m *ProtoUser) GetUid() uint32 {
	if m != nil && m.Uid != nil {
		return *m.Uid
	}
	return 0
}

func (m *ProtoUser) GetNickName() string {
	if m != nil && m.NickName != nil {
		return *m.NickName
	}
	return ""
}

func (m *ProtoUser) GetWeixin() string {
	if m != nil && m.Weixin != nil {
		return *m.Weixin
	}
	return ""
}

func (m *ProtoUser) GetSeat() uint32 {
	if m != nil && m.Seat != nil {
		return *m.Seat
	}
	return 0
}

func (m *ProtoUser) GetSex() uint32 {
	if m != nil && m.Sex != nil {
		return *m.Sex
	}
	return 0
}

func (m *ProtoUser) GetPhoto() string {
	if m != nil && m.Photo != nil {
		return *m.Photo
	}
	return ""
}

func (m *ProtoUser) GetAddress() string {
	if m != nil && m.Address != nil {
		return *m.Address
	}
	return ""
}

func (m *ProtoUser) GetIP() string {
	if m != nil && m.IP != nil {
		return *m.IP
	}
	return ""
}

func (m *ProtoUser) GetTerminal() string {
	if m != nil && m.Terminal != nil {
		return *m.Terminal
	}
	return ""
}

func (m *ProtoUser) GetRoomCard() uint32 {
	if m != nil && m.RoomCard != nil {
		return *m.RoomCard
	}
	return 0
}

func (m *ProtoUser) GetReady() bool {
	if m != nil && m.Ready != nil {
		return *m.Ready
	}
	return false
}

func (m *ProtoUser) GetInviteCode() uint32 {
	if m != nil && m.InviteCode != nil {
		return *m.InviteCode
	}
	return 0
}

func (m *ProtoUser) GetScore() int32 {
	if m != nil && m.Score != nil {
		return *m.Score
	}
	return 0
}

func (m *ProtoUser) GetIsInputted() bool {
	if m != nil && m.IsInputted != nil {
		return *m.IsInputted
	}
	return false
}

func (m *ProtoUser) GetRole() uint32 {
	if m != nil && m.Role != nil {
		return *m.Role
	}
	return 0
}

func (m *ProtoUser) GetIsSporting() bool {
	if m != nil && m.IsSporting != nil {
		return *m.IsSporting
	}
	return false
}

func (m *ProtoUser) GetWeixinno() string {
	if m != nil && m.Weixinno != nil {
		return *m.Weixinno
	}
	return ""
}

func (m *ProtoUser) GetUpperid() uint32 {
	if m != nil && m.Upperid != nil {
		return *m.Upperid
	}
	return 0
}

func (m *ProtoUser) GetGold() int64 {
	if m != nil && m.Gold != nil {
		return *m.Gold
	}
	return 0
}

func (m *ProtoUser) GetCarryGold() int64 {
	if m != nil && m.CarryGold != nil {
		return *m.CarryGold
	}
	return 0
}

func (m *ProtoUser) GetSafeGold() int64 {
	if m != nil && m.SafeGold != nil {
		return *m.SafeGold
	}
	return 0
}

func (m *ProtoUser) GetDiamond() int64 {
	if m != nil && m.Diamond != nil {
		return *m.Diamond
	}
	return 0
}

func (m *ProtoUser) GetCarryDiamond() int64 {
	if m != nil && m.CarryDiamond != nil {
		return *m.CarryDiamond
	}
	return 0
}

func (m *ProtoUser) GetSafeDiamond() int64 {
	if m != nil && m.SafeDiamond != nil {
		return *m.SafeDiamond
	}
	return 0
}

func (m *ProtoUser) GetLoginTypes() string {
	if m != nil && m.LoginTypes != nil {
		return *m.LoginTypes
	}
	return ""
}

func (m *ProtoUser) GetMatchCoin() int64 {
	if m != nil && m.MatchCoin != nil {
		return *m.MatchCoin
	}
	return 0
}

func (m *ProtoUser) GetIsAgent() bool {
	if m != nil && m.IsAgent != nil {
		return *m.IsAgent
	}
	return false
}

func (m *ProtoUser) GetIsChooseSeat() bool {
	if m != nil && m.IsChooseSeat != nil {
		return *m.IsChooseSeat
	}
	return false
}

func (m *ProtoUser) GetIsSuper() int32 {
	if m != nil && m.IsSuper != nil {
		return *m.IsSuper
	}
	return 0
}

func (m *ProtoUser) GetCoupons() uint32 {
	if m != nil && m.Coupons != nil {
		return *m.Coupons
	}
	return 0
}

func (m *ProtoUser) GetDescription() string {
	if m != nil && m.Description != nil {
		return *m.Description
	}
	return ""
}

func (m *ProtoUser) GetPhone() string {
	if m != nil && m.Phone != nil {
		return *m.Phone
	}
	return ""
}

func init() {
	proto.RegisterEnum("protocol.PF", PF_name, PF_value)
	proto.RegisterEnum("protocol.PlayerRole", PlayerRole_name, PlayerRole_value)
}
