// Code generated by protoc-gen-go.
// source: login_config.proto
// DO NOT EDIT!

package protocol

import proto "code.google.com/p/goprotobuf/proto"
import json "encoding/json"
import math "math"

// Reference proto, json, and math imports to suppress error if they are not otherwise used.
var _ = proto.Marshal
var _ = &json.SyntaxError{}
var _ = math.Inf

// 游戏全局配置
type CGlobal struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *CGlobal) Reset()         { *m = CGlobal{} }
func (m *CGlobal) String() string { return proto.CompactTextString(m) }
func (*CGlobal) ProtoMessage()    {}

type SGlobal struct {
	Error            *uint32 `protobuf:"varint,1,opt" json:"Error,omitempty"`
	GameTimeout      *uint32 `protobuf:"varint,2,opt" json:"GameTimeout,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *SGlobal) Reset()         { *m = SGlobal{} }
func (m *SGlobal) String() string { return proto.CompactTextString(m) }
func (*SGlobal) ProtoMessage()    {}

func (m *SGlobal) GetError() uint32 {
	if m != nil && m.Error != nil {
		return *m.Error
	}
	return 0
}

func (m *SGlobal) GetGameTimeout() uint32 {
	if m != nil && m.GameTimeout != nil {
		return *m.GameTimeout
	}
	return 0
}

func init() {
}
