// Code generated by protoc-gen-go.
// source: login_agent.proto
// DO NOT EDIT!

package protocol

import proto "code.google.com/p/goprotobuf/proto"
import json "encoding/json"
import math "math"

// Reference proto, json, and math imports to suppress error if they are not otherwise used.
var _ = proto.Marshal
var _ = &json.SyntaxError{}
var _ = math.Inf

// 获取上级代码信息
type CGetUpperInfo struct {
	Appid            *uint32 `protobuf:"varint,1,opt" json:"Appid,omitempty"`
	Uid              *uint32 `protobuf:"varint,2,opt" json:"Uid,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *CGetUpperInfo) Reset()         { *m = CGetUpperInfo{} }
func (m *CGetUpperInfo) String() string { return proto.CompactTextString(m) }
func (*CGetUpperInfo) ProtoMessage()    {}

func (m *CGetUpperInfo) GetAppid() uint32 {
	if m != nil && m.Appid != nil {
		return *m.Appid
	}
	return 0
}

func (m *CGetUpperInfo) GetUid() uint32 {
	if m != nil && m.Uid != nil {
		return *m.Uid
	}
	return 0
}

//  获取上级代码信息
type SGetUpperInfo struct {
	State            *uint32 `protobuf:"varint,1,opt" json:"State,omitempty"`
	Weixinno         *string `protobuf:"bytes,2,opt" json:"Weixinno,omitempty"`
	Upperid          *uint32 `protobuf:"varint,3,opt" json:"Upperid,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *SGetUpperInfo) Reset()         { *m = SGetUpperInfo{} }
func (m *SGetUpperInfo) String() string { return proto.CompactTextString(m) }
func (*SGetUpperInfo) ProtoMessage()    {}

func (m *SGetUpperInfo) GetState() uint32 {
	if m != nil && m.State != nil {
		return *m.State
	}
	return 0
}

func (m *SGetUpperInfo) GetWeixinno() string {
	if m != nil && m.Weixinno != nil {
		return *m.Weixinno
	}
	return ""
}

func (m *SGetUpperInfo) GetUpperid() uint32 {
	if m != nil && m.Upperid != nil {
		return *m.Upperid
	}
	return 0
}

func init() {
}
