// Code generated by protoc-gen-go.
// source: login_feedback.proto
// DO NOT EDIT!

package protocol

import proto "code.google.com/p/goprotobuf/proto"
import json "encoding/json"
import math "math"

// Reference proto, json, and math imports to suppress error if they are not otherwise used.
var _ = proto.Marshal
var _ = &json.SyntaxError{}
var _ = math.Inf

// CFeedback 反馈
type CFeedBack struct {
	Content          *string `protobuf:"bytes,1,opt" json:"Content,omitempty"`
	Type             *uint32 `protobuf:"varint,2,opt" json:"Type,omitempty"`
	Photo            *string `protobuf:"bytes,3,opt" json:"Photo,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *CFeedBack) Reset()         { *m = CFeedBack{} }
func (m *CFeedBack) String() string { return proto.CompactTextString(m) }
func (*CFeedBack) ProtoMessage()    {}

func (m *CFeedBack) GetContent() string {
	if m != nil && m.Content != nil {
		return *m.Content
	}
	return ""
}

func (m *CFeedBack) GetType() uint32 {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return 0
}

func (m *CFeedBack) GetPhoto() string {
	if m != nil && m.Photo != nil {
		return *m.Photo
	}
	return ""
}

// SFeedback 反馈
type SFeedBack struct {
	Error            *uint32 `protobuf:"varint,1,opt" json:"Error,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *SFeedBack) Reset()         { *m = SFeedBack{} }
func (m *SFeedBack) String() string { return proto.CompactTextString(m) }
func (*SFeedBack) ProtoMessage()    {}

func (m *SFeedBack) GetError() uint32 {
	if m != nil && m.Error != nil {
		return *m.Error
	}
	return 0
}

func init() {
}
