// Code generated by protoc-gen-go.
// source: login_userinfo.proto
// DO NOT EDIT!

package protocol

import proto "code.google.com/p/goprotobuf/proto"
import json "encoding/json"
import math "math"

// Reference proto, json, and math imports to suppress error if they are not otherwise used.
var _ = proto.Marshal
var _ = &json.SyntaxError{}
var _ = math.Inf

// 获取玩家详细数据
type CUserData struct {
	Uid              *uint32 `protobuf:"varint,1,opt" json:"Uid,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *CUserData) Reset()         { *m = CUserData{} }
func (m *CUserData) String() string { return proto.CompactTextString(m) }
func (*CUserData) ProtoMessage()    {}

func (m *CUserData) GetUid() uint32 {
	if m != nil && m.Uid != nil {
		return *m.Uid
	}
	return 0
}

// 获取玩家详细数据
type SUserData struct {
	Error            *uint32 `protobuf:"varint,1,opt" json:"Error,omitempty"`
	Uid              *uint32 `protobuf:"varint,2,opt" json:"Uid,omitempty"`
	Nickname         *string `protobuf:"bytes,3,opt" json:"Nickname,omitempty"`
	Sex              *uint32 `protobuf:"varint,4,opt" json:"Sex,omitempty"`
	Icon             *string `protobuf:"bytes,5,opt" json:"Icon,omitempty"`
	Lastloginip      *string `protobuf:"bytes,6,opt" json:"Lastloginip,omitempty"`
	Parentuid        *uint32 `protobuf:"varint,7,opt" json:"Parentuid,omitempty"`
	Parentwechatid   *string `protobuf:"bytes,8,opt" json:"Parentwechatid,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *SUserData) Reset()         { *m = SUserData{} }
func (m *SUserData) String() string { return proto.CompactTextString(m) }
func (*SUserData) ProtoMessage()    {}

func (m *SUserData) GetError() uint32 {
	if m != nil && m.Error != nil {
		return *m.Error
	}
	return 0
}

func (m *SUserData) GetUid() uint32 {
	if m != nil && m.Uid != nil {
		return *m.Uid
	}
	return 0
}

func (m *SUserData) GetNickname() string {
	if m != nil && m.Nickname != nil {
		return *m.Nickname
	}
	return ""
}

func (m *SUserData) GetSex() uint32 {
	if m != nil && m.Sex != nil {
		return *m.Sex
	}
	return 0
}

func (m *SUserData) GetIcon() string {
	if m != nil && m.Icon != nil {
		return *m.Icon
	}
	return ""
}

func (m *SUserData) GetLastloginip() string {
	if m != nil && m.Lastloginip != nil {
		return *m.Lastloginip
	}
	return ""
}

func (m *SUserData) GetParentuid() uint32 {
	if m != nil && m.Parentuid != nil {
		return *m.Parentuid
	}
	return 0
}

func (m *SUserData) GetParentwechatid() string {
	if m != nil && m.Parentwechatid != nil {
		return *m.Parentwechatid
	}
	return ""
}

// 获取玩家常用数据
type CLessUserData struct {
	Uid              *uint32 `protobuf:"varint,1,opt" json:"Uid,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *CLessUserData) Reset()         { *m = CLessUserData{} }
func (m *CLessUserData) String() string { return proto.CompactTextString(m) }
func (*CLessUserData) ProtoMessage()    {}

func (m *CLessUserData) GetUid() uint32 {
	if m != nil && m.Uid != nil {
		return *m.Uid
	}
	return 0
}

// 获取玩家简单的数据
type SLessUserData struct {
	Error            *uint32       `protobuf:"varint,1,opt" json:"Error,omitempty"`
	Data             *LessUserData `protobuf:"bytes,2,opt" json:"Data,omitempty"`
	XXX_unrecognized []byte        `json:"-"`
}

func (m *SLessUserData) Reset()         { *m = SLessUserData{} }
func (m *SLessUserData) String() string { return proto.CompactTextString(m) }
func (*SLessUserData) ProtoMessage()    {}

func (m *SLessUserData) GetError() uint32 {
	if m != nil && m.Error != nil {
		return *m.Error
	}
	return 0
}

func (m *SLessUserData) GetData() *LessUserData {
	if m != nil {
		return m.Data
	}
	return nil
}

// 玩家信息改变推送
type SChangeUserData struct {
	Uid              *uint32 `protobuf:"varint,1,opt" json:"Uid,omitempty"`
	Gold             *int64  `protobuf:"varint,2,opt" json:"Gold,omitempty"`
	CarryGold        *int64  `protobuf:"varint,3,opt" json:"CarryGold,omitempty"`
	SafeGold         *int64  `protobuf:"varint,4,opt" json:"SafeGold,omitempty"`
	CarryDiamond     *int64  `protobuf:"varint,5,opt" json:"CarryDiamond,omitempty"`
	RoomCard         *int32  `protobuf:"varint,6,opt" json:"RoomCard,omitempty"`
	IsAgent          *bool   `protobuf:"varint,7,opt" json:"IsAgent,omitempty"`
	Diamond          *int64  `protobuf:"varint,8,opt" json:"Diamond,omitempty"`
	SafeDiamond      *int64  `protobuf:"varint,9,opt" json:"SafeDiamond,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *SChangeUserData) Reset()         { *m = SChangeUserData{} }
func (m *SChangeUserData) String() string { return proto.CompactTextString(m) }
func (*SChangeUserData) ProtoMessage()    {}

func (m *SChangeUserData) GetUid() uint32 {
	if m != nil && m.Uid != nil {
		return *m.Uid
	}
	return 0
}

func (m *SChangeUserData) GetGold() int64 {
	if m != nil && m.Gold != nil {
		return *m.Gold
	}
	return 0
}

func (m *SChangeUserData) GetCarryGold() int64 {
	if m != nil && m.CarryGold != nil {
		return *m.CarryGold
	}
	return 0
}

func (m *SChangeUserData) GetSafeGold() int64 {
	if m != nil && m.SafeGold != nil {
		return *m.SafeGold
	}
	return 0
}

func (m *SChangeUserData) GetCarryDiamond() int64 {
	if m != nil && m.CarryDiamond != nil {
		return *m.CarryDiamond
	}
	return 0
}

func (m *SChangeUserData) GetRoomCard() int32 {
	if m != nil && m.RoomCard != nil {
		return *m.RoomCard
	}
	return 0
}

func (m *SChangeUserData) GetIsAgent() bool {
	if m != nil && m.IsAgent != nil {
		return *m.IsAgent
	}
	return false
}

func (m *SChangeUserData) GetDiamond() int64 {
	if m != nil && m.Diamond != nil {
		return *m.Diamond
	}
	return 0
}

func (m *SChangeUserData) GetSafeDiamond() int64 {
	if m != nil && m.SafeDiamond != nil {
		return *m.SafeDiamond
	}
	return 0
}

func init() {
}
